services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # WebSocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  control-cove:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: control-cove
    ports:
      - "8080:8080"
    environment:
      MQTT_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: ${MQTT_USERNAME:-dev}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-dev}
    volumes:
      - ./logs:/var/log/control-cove
    depends_on:
      - mosquitto
    restart: unless-stopped
